// <auto-generated />
using System;
using M4HW6;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace M4HW6.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230114124438_NewSong")]
    partial class NewSong
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("M4HW6.Entities.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtistId"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InstagramUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.HasKey("ArtistId");

                    b.ToTable("Artist", (string)null);
                });

            modelBuilder.Entity("M4HW6.Entities.ArtistAndSong", b =>
                {
                    b.Property<int>("ArtistAndSongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtistAndSongId"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("money");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ArtistAndSongId");

                    b.HasIndex("ArtistId");

                    b.HasIndex("SongId");

                    b.ToTable("ArtistAndSong", (string)null);
                });

            modelBuilder.Entity("M4HW6.Entities.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreId"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GenreId");

                    b.ToTable("Genre", (string)null);

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            Title = "folk"
                        },
                        new
                        {
                            GenreId = 2,
                            Title = "rock"
                        },
                        new
                        {
                            GenreId = 3,
                            Title = "classical"
                        },
                        new
                        {
                            GenreId = 4,
                            Title = "pop"
                        },
                        new
                        {
                            GenreId = 5,
                            Title = "jazz"
                        },
                        new
                        {
                            GenreId = 6,
                            Title = "latin"
                        });
                });

            modelBuilder.Entity("M4HW6.Entities.Song", b =>
                {
                    b.Property<int>("SongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SongId"));

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleasedDate")
                        .HasColumnType("date");

                    b.Property<string>("Tite")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("SongId");

                    b.HasIndex("GenreId");

                    b.ToTable("Song", (string)null);

                    b.HasData(
                        new
                        {
                            SongId = 1,
                            Duration = 10,
                            GenreId = 1,
                            ReleasedDate = new DateTime(2020, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tite = "Runar"
                        },
                        new
                        {
                            SongId = 2,
                            Duration = 4,
                            GenreId = 1,
                            ReleasedDate = new DateTime(2021, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tite = "Berserkir"
                        },
                        new
                        {
                            SongId = 3,
                            Duration = 5,
                            GenreId = 1,
                            ReleasedDate = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tite = "Helfa"
                        },
                        new
                        {
                            SongId = 4,
                            Duration = 4,
                            GenreId = 2,
                            ReleasedDate = new DateTime(2013, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tite = "Bury Them Deep"
                        },
                        new
                        {
                            SongId = 5,
                            Duration = 2,
                            GenreId = 3,
                            ReleasedDate = new DateTime(1853, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tite = "Ave Maria"
                        },
                        new
                        {
                            SongId = 6,
                            Duration = 6,
                            GenreId = 4,
                            ReleasedDate = new DateTime(2019, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tite = "Credo"
                        },
                        new
                        {
                            SongId = 7,
                            Duration = 5,
                            GenreId = 5,
                            ReleasedDate = new DateTime(2011, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tite = "Ain't Got Nobody"
                        },
                        new
                        {
                            SongId = 8,
                            Duration = 5,
                            GenreId = 6,
                            ReleasedDate = new DateTime(2013, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tite = "Despacito"
                        });
                });

            modelBuilder.Entity("M4HW6.Entities.ArtistAndSong", b =>
                {
                    b.HasOne("M4HW6.Entities.Artist", "Artist")
                        .WithMany("ArtistsAndSongs")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("M4HW6.Entities.Song", "Song")
                        .WithMany("ArtistsAndSongs")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("M4HW6.Entities.Song", b =>
                {
                    b.HasOne("M4HW6.Entities.Genre", "Genre")
                        .WithMany("Songs")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("M4HW6.Entities.Artist", b =>
                {
                    b.Navigation("ArtistsAndSongs");
                });

            modelBuilder.Entity("M4HW6.Entities.Genre", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("M4HW6.Entities.Song", b =>
                {
                    b.Navigation("ArtistsAndSongs");
                });
#pragma warning restore 612, 618
        }
    }
}
